#!/usr/bin/env python3
"""Build deterministic SCAF Consumption Selection YAML from validated inputs.

The builder consumes one exact Effective Project Profile snapshot plus explicit,
non-authoritative selection inputs. It validates the source profile before
reading profile state, deterministically constructs the accepted rc03
Consumption Selection representation, and self-validates the generated bytes
through the accepted rc05 source-aware validator before returning or emitting
output.

Building is not applicability inference, Pattern selection, context-source
resolution, engineering approval, verification/compliance, release, or closure.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable, Sequence

try:
    import yaml
except ImportError as exc:  # pragma: no cover - CLI environment only
    raise SystemExit(
        "Missing dependency: PyYAML. Install "
        "tools/scaf_consumption_selection_builder/requirements.txt"
    ) from exc

from tools.scaf_consumption_selection_validator.validator import (
    validate_consumption_selection,
)
from tools.scaf_effective_project_profile_validator.validator import (
    StrictEffectiveProjectProfileLoader,
    validate_effective_project_profile,
)

__all__ = (
    "ConsumptionSelectionBuildError",
    "build_consumption_selection",
    "main",
)

DEFAULT_PROFILE_PATH = Path("examples/effective-project-profile.yaml")
DEFAULT_PROJECT_APPLICATION_PATH = Path("examples/project-application.yaml")
SELECTION_SCHEMA_PATH = Path("schemas/consumption-selection.schema.json")
PROFILE_SCHEMA_PATH = Path("schemas/effective-project-profile.schema.json")
PROJECT_APPLICATION_SCHEMA_PATH = Path("schemas/project-application.schema.json")
AUTHORITY_REGISTRY_PATH = Path("authority-registry.yaml")
AUTHORITY_SCHEMA_PATH = Path("schemas/authority-registry.schema.json")
NORMATIVE_ROOT_PATH = Path("docs/normative")

AUTHORITY_MODE_ALL_DOMAIN = "all_domain"
AUTHORITY_MODE_EXPLICIT_SET = "explicit_set"


class ConsumptionSelectionBuildError(RuntimeError):
    """Raised when deterministic validated Consumption Selection build fails."""


def _resolve_project_path(repo_root: Path, path: Path | None, default: Path) -> Path:
    if path is None:
        return (repo_root / default).resolve()
    if path.is_absolute():
        return path.resolve()
    return (Path.cwd() / path).resolve()


def _read_utf8_bytes(path: Path, label: str) -> bytes:
    try:
        data = path.read_bytes()
        data.decode("utf-8")
        return data
    except (OSError, UnicodeError) as exc:
        raise ConsumptionSelectionBuildError(
            f"{label}: cannot read UTF-8 source {path.as_posix()}: {exc}"
        ) from exc


def _read_normative_snapshot(repo_root: Path) -> dict[str, bytes]:
    source_root = repo_root / NORMATIVE_ROOT_PATH
    snapshot: dict[str, bytes] = {}
    try:
        for source_file in sorted(source_root.glob("*.md")):
            data = source_file.read_bytes()
            data.decode("utf-8")
            snapshot[source_file.name] = data
    except (OSError, UnicodeError) as exc:
        raise ConsumptionSelectionBuildError(
            f"cannot read canonical normative-source snapshot: {exc}"
        ) from exc
    if not snapshot:
        raise ConsumptionSelectionBuildError(
            "canonical normative-source snapshot is empty"
        )
    return snapshot


def _prepare_validation_boundary(
    boundary_root: Path,
    *,
    selection_schema_bytes: bytes,
    profile_schema_bytes: bytes,
    project_application_schema_bytes: bytes,
    authority_bytes: bytes,
    authority_schema_bytes: bytes,
    normative_snapshot: dict[str, bytes],
) -> None:
    try:
        (boundary_root / "schemas").mkdir(parents=True, exist_ok=True)
        (boundary_root / NORMATIVE_ROOT_PATH).mkdir(parents=True, exist_ok=True)
        (boundary_root / SELECTION_SCHEMA_PATH).write_bytes(selection_schema_bytes)
        (boundary_root / PROFILE_SCHEMA_PATH).write_bytes(profile_schema_bytes)
        (boundary_root / PROJECT_APPLICATION_SCHEMA_PATH).write_bytes(
            project_application_schema_bytes
        )
        (boundary_root / AUTHORITY_REGISTRY_PATH).write_bytes(authority_bytes)
        (boundary_root / AUTHORITY_SCHEMA_PATH).write_bytes(authority_schema_bytes)
        for filename, data in normative_snapshot.items():
            (boundary_root / NORMATIVE_ROOT_PATH / filename).write_bytes(data)
    except OSError as exc:
        raise ConsumptionSelectionBuildError(
            f"cannot create private builder validation boundary: {exc}"
        ) from exc


def _load_json_bytes(data: bytes, label: str) -> dict[str, Any]:
    try:
        loaded = json.loads(data.decode("utf-8"))
    except (UnicodeError, json.JSONDecodeError) as exc:
        raise ConsumptionSelectionBuildError(f"{label}: cannot load JSON: {exc}") from exc
    if not isinstance(loaded, dict):
        raise ConsumptionSelectionBuildError(f"{label}: JSON root must be an object")
    return loaded


def _load_validated_profile(path: Path) -> dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
        data = yaml.load(text, Loader=StrictEffectiveProjectProfileLoader)
    except (OSError, UnicodeError, yaml.YAMLError) as exc:
        raise ConsumptionSelectionBuildError(
            f"validated Effective Project Profile snapshot could not be loaded: {exc}"
        ) from exc
    if not isinstance(data, dict) or not isinstance(data.get("entries"), list):
        raise ConsumptionSelectionBuildError(
            "validated Effective Project Profile snapshot did not expose an entries list"
        )
    return data


def _schema_contract(selection_schema: dict[str, Any]) -> tuple[str, str, tuple[str, ...]]:
    try:
        selection_kind = selection_schema["properties"]["selection_kind"]["const"]
        representation_release = selection_schema["properties"]["representation_release"][
            "const"
        ]
        profile_states = tuple(selection_schema["$defs"]["profileState"]["enum"])
    except (KeyError, TypeError) as exc:
        raise ConsumptionSelectionBuildError(
            "repository-owned Consumption Selection schema does not expose accepted "
            "selection_kind / representation_release / profileState contract"
        ) from exc
    if not isinstance(selection_kind, str) or not selection_kind:
        raise ConsumptionSelectionBuildError("invalid selection_kind schema constant")
    if not isinstance(representation_release, str) or not representation_release:
        raise ConsumptionSelectionBuildError(
            "invalid Consumption Selection representation_release schema constant"
        )
    if (
        len(profile_states) != 4
        or any(not isinstance(state, str) or not state for state in profile_states)
        or len(set(profile_states)) != len(profile_states)
    ):
        raise ConsumptionSelectionBuildError(
            "repository-owned Consumption Selection schema exposes invalid profile-state order"
        )
    return selection_kind, representation_release, profile_states


def _normalize_unique_strings(
    values: Sequence[str] | Iterable[str],
    *,
    label: str,
    allow_empty_values: bool = False,
) -> tuple[str, ...]:
    if isinstance(values, str):
        raise ConsumptionSelectionBuildError(f"{label} must be a sequence, not one string")
    normalized = tuple(values)
    for value in normalized:
        if not isinstance(value, str):
            raise ConsumptionSelectionBuildError(f"{label} values must be strings")
        if not allow_empty_values and value == "":
            raise ConsumptionSelectionBuildError(f"{label} values must be non-empty")
    if len(set(normalized)) != len(normalized):
        raise ConsumptionSelectionBuildError(f"{label} contains duplicate values")
    return normalized


def _canonical_state_selector(
    states: Sequence[str] | Iterable[str],
    profile_state_order: tuple[str, ...],
) -> tuple[str, ...]:
    values = _normalize_unique_strings(states, label="state_selector")
    unknown = sorted(set(values) - set(profile_state_order))
    if unknown:
        raise ConsumptionSelectionBuildError(
            "state_selector contains unsupported state(s): " + ", ".join(unknown)
        )
    rank = {state: index for index, state in enumerate(profile_state_order)}
    return tuple(sorted(values, key=rank.__getitem__))


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _serialize_selection(
    *,
    selection_kind: str,
    representation_release: str,
    profile_bytes: bytes,
    profile: dict[str, Any],
    selection_purpose: str,
    state_selector: tuple[str, ...],
    authority_mode: str,
    authority_ids: tuple[str, ...],
    omission_basis: str | None,
    selected_entries: list[dict[str, str]],
    selection_class: str,
) -> bytes:
    lines = [
        f"selection_kind: {_yaml_string(selection_kind)}",
        f"representation_release: {_yaml_string(representation_release)}",
        "source_profile_binding:",
        "  effective_project_profile_source_sha256: "
        + _yaml_string(hashlib.sha256(profile_bytes).hexdigest()),
        f"  scaf_source_release: {_yaml_string(profile['scaf_source_release'])}",
        f"  project_scope_ref: {_yaml_string(profile['project_scope_ref'])}",
        "  project_application_source_sha256: "
        + _yaml_string(profile["project_application_source_sha256"]),
        f"selection_purpose: {_yaml_string(selection_purpose)}",
    ]
    if state_selector:
        lines.append("state_selector:")
        for state in state_selector:
            lines.append(f"  - {_yaml_string(state)}")
    else:
        lines.append("state_selector: []")

    lines.append("authority_selector:")
    lines.append(f"  mode: {_yaml_string(authority_mode)}")
    if authority_mode == AUTHORITY_MODE_EXPLICIT_SET:
        if authority_ids:
            lines.append("  scaf_authority_ids:")
            for authority_id in authority_ids:
                lines.append(f"    - {_yaml_string(authority_id)}")
        else:
            lines.append("  scaf_authority_ids: []")

    lines.append("bounded_omission:")
    if omission_basis is None:
        lines.append("  applied: false")
    else:
        lines.append("  applied: true")
        lines.append(f"  basis: {_yaml_string(omission_basis)}")

    if selected_entries:
        lines.append("selected_entries:")
        for entry in selected_entries:
            lines.append(f"  - scaf_authority_id: {_yaml_string(entry['scaf_authority_id'])}")
            lines.append(f"    profile_state: {_yaml_string(entry['profile_state'])}")
            record_id = entry.get("project_application_record_id")
            if record_id is not None:
                lines.append(
                    f"    project_application_record_id: {_yaml_string(record_id)}"
                )
    else:
        lines.append("selected_entries: []")

    lines.append(f"selection_class: {_yaml_string(selection_class)}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def build_consumption_selection(
    repo_root: Path,
    selection_purpose: str,
    state_selector: Sequence[str] | Iterable[str] = (),
    *,
    authority_mode: str = AUTHORITY_MODE_ALL_DOMAIN,
    authority_ids: Sequence[str] | Iterable[str] = (),
    omitted_authority_ids: Sequence[str] | Iterable[str] = (),
    omission_basis: str | None = None,
    profile_path: Path | None = None,
    project_application_path: Path | None = None,
) -> bytes:
    """Build one canonical Consumption Selection from validated source snapshots.

    The caller selects only descriptive purpose, the bounded state selector,
    exact authority selector, and an optional exact set of eligible authority
    IDs to omit under one descriptive omission basis. The builder performs no
    ranking, token-budget calculation, semantic similarity, scope resolution,
    applicability inference, or context-content resolution.

    Returned bytes are released only after accepted rc05 source-aware
    Consumption Selection validation passes against the same captured profile
    and Project Application snapshots plus a private repository-owned source
    boundary.
    """

    if not isinstance(selection_purpose, str) or selection_purpose == "":
        raise ConsumptionSelectionBuildError(
            "selection_purpose must be a non-empty descriptive string"
        )
    if authority_mode not in (AUTHORITY_MODE_ALL_DOMAIN, AUTHORITY_MODE_EXPLICIT_SET):
        raise ConsumptionSelectionBuildError(
            "authority_mode must be 'all_domain' or 'explicit_set'"
        )
    if omission_basis is not None and (
        not isinstance(omission_basis, str) or omission_basis == ""
    ):
        raise ConsumptionSelectionBuildError(
            "omission_basis must be None or a non-empty descriptive string"
        )

    repo_root = repo_root.resolve()
    profile_path = _resolve_project_path(repo_root, profile_path, DEFAULT_PROFILE_PATH)
    project_application_path = _resolve_project_path(
        repo_root, project_application_path, DEFAULT_PROJECT_APPLICATION_PATH
    )

    profile_bytes = _read_utf8_bytes(profile_path, "Effective Project Profile")
    project_application_bytes = _read_utf8_bytes(
        project_application_path, "Project Application"
    )
    selection_schema_bytes = _read_utf8_bytes(
        repo_root / SELECTION_SCHEMA_PATH, "Consumption Selection schema"
    )
    profile_schema_bytes = _read_utf8_bytes(
        repo_root / PROFILE_SCHEMA_PATH, "Effective Project Profile schema"
    )
    project_application_schema_bytes = _read_utf8_bytes(
        repo_root / PROJECT_APPLICATION_SCHEMA_PATH, "Project Application schema"
    )
    authority_bytes = _read_utf8_bytes(
        repo_root / AUTHORITY_REGISTRY_PATH, "authority registry"
    )
    authority_schema_bytes = _read_utf8_bytes(
        repo_root / AUTHORITY_SCHEMA_PATH, "authority schema"
    )
    normative_snapshot = _read_normative_snapshot(repo_root)

    selection_schema = _load_json_bytes(
        selection_schema_bytes, "Consumption Selection schema"
    )
    selection_kind, representation_release, profile_state_order = _schema_contract(
        selection_schema
    )
    canonical_states = _canonical_state_selector(state_selector, profile_state_order)
    exact_authority_ids = _normalize_unique_strings(
        authority_ids, label="authority_ids"
    )
    exact_omitted_ids = _normalize_unique_strings(
        omitted_authority_ids, label="omitted_authority_ids"
    )

    if authority_mode == AUTHORITY_MODE_ALL_DOMAIN and exact_authority_ids:
        raise ConsumptionSelectionBuildError(
            "authority_ids must be empty when authority_mode is all_domain"
        )
    if omission_basis is None and exact_omitted_ids:
        raise ConsumptionSelectionBuildError(
            "omitted_authority_ids require a non-empty omission_basis"
        )

    with tempfile.TemporaryDirectory(prefix="scaf-consumption-selection-build-") as tmp:
        boundary_root = Path(tmp) / "repo"
        boundary_root.mkdir(parents=True, exist_ok=True)
        _prepare_validation_boundary(
            boundary_root,
            selection_schema_bytes=selection_schema_bytes,
            profile_schema_bytes=profile_schema_bytes,
            project_application_schema_bytes=project_application_schema_bytes,
            authority_bytes=authority_bytes,
            authority_schema_bytes=authority_schema_bytes,
            normative_snapshot=normative_snapshot,
        )

        profile_snapshot = boundary_root / "selected-effective-project-profile.yaml"
        project_snapshot = boundary_root / "selected-project-application.yaml"
        profile_snapshot.write_bytes(profile_bytes)
        project_snapshot.write_bytes(project_application_bytes)

        profile_report = validate_effective_project_profile(
            boundary_root,
            profile_snapshot,
            project_snapshot,
        )
        if not profile_report.passed:
            raise ConsumptionSelectionBuildError(
                "selected Effective Project Profile snapshot failed frozen v0.0.6 "
                "source-aware validation: " + "; ".join(profile_report.errors)
            )

        profile = _load_validated_profile(profile_snapshot)
        profile_entries = profile["entries"]
        profile_index = {entry["scaf_authority_id"]: entry for entry in profile_entries}
        domain_ids = tuple(sorted(profile_index))
        domain_set = set(domain_ids)

        if authority_mode == AUTHORITY_MODE_ALL_DOMAIN:
            canonical_authority_ids: tuple[str, ...] = ()
            allowed_ids = domain_set
        else:
            unknown_authority_ids = sorted(set(exact_authority_ids) - domain_set)
            if unknown_authority_ids:
                raise ConsumptionSelectionBuildError(
                    "authority_ids contain ID(s) outside the validated source-profile "
                    "domain: " + ", ".join(unknown_authority_ids)
                )
            canonical_authority_ids = tuple(sorted(exact_authority_ids))
            allowed_ids = set(canonical_authority_ids)

        selected_state_set = set(canonical_states)
        eligible_set = {
            authority_id
            for authority_id, entry in profile_index.items()
            if entry["profile_state"] in selected_state_set and authority_id in allowed_ids
        }

        unknown_omitted_ids = sorted(set(exact_omitted_ids) - domain_set)
        if unknown_omitted_ids:
            raise ConsumptionSelectionBuildError(
                "omitted_authority_ids contain ID(s) outside the validated source-profile "
                "domain: " + ", ".join(unknown_omitted_ids)
            )
        ineligible_omitted_ids = sorted(set(exact_omitted_ids) - eligible_set)
        if ineligible_omitted_ids:
            raise ConsumptionSelectionBuildError(
                "omitted_authority_ids must be predicate-eligible; ineligible ID(s): "
                + ", ".join(ineligible_omitted_ids)
            )

        omitted_set = set(exact_omitted_ids)
        included_set = eligible_set - omitted_set
        excluded_set = domain_set - eligible_set

        selected_entries: list[dict[str, str]] = []
        for authority_id in sorted(included_set):
            source_entry = profile_index[authority_id]
            projected = {
                "scaf_authority_id": authority_id,
                "profile_state": source_entry["profile_state"],
            }
            record_id = source_entry.get("project_application_record_id")
            if record_id is not None:
                projected["project_application_record_id"] = record_id
            selected_entries.append(projected)

        selection_class = (
            "complete"
            if included_set == domain_set and not omitted_set and not excluded_set
            else "filtered"
        )

        generated_bytes = _serialize_selection(
            selection_kind=selection_kind,
            representation_release=representation_release,
            profile_bytes=profile_bytes,
            profile=profile,
            selection_purpose=selection_purpose,
            state_selector=canonical_states,
            authority_mode=authority_mode,
            authority_ids=canonical_authority_ids,
            omission_basis=omission_basis,
            selected_entries=selected_entries,
            selection_class=selection_class,
        )

        generated_selection = boundary_root / "generated-consumption-selection.yaml"
        generated_selection.write_bytes(generated_bytes)
        generated_report = validate_consumption_selection(
            boundary_root,
            generated_selection,
            profile_snapshot,
            project_snapshot,
        )
        if not generated_report.passed:
            raise ConsumptionSelectionBuildError(
                "internally generated Consumption Selection failed accepted rc05 "
                "representation/source validation: " + "; ".join(generated_report.errors)
            )

        return generated_bytes


def _default_repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Build one deterministic canonical SCAF Consumption Selection from an exact "
            "validated Effective Project Profile and explicit bounded selection inputs. "
            "Output is canonical YAML on stdout."
        )
    )
    parser.add_argument(
        "--purpose",
        required=True,
        help="Non-empty descriptive selection purpose; not an engineering authority input.",
    )
    parser.add_argument(
        "--state",
        action="append",
        default=[],
        help=(
            "Frozen Effective Project Profile state to include in the eligibility predicate. "
            "Repeat as needed; zero states is a valid zero-eligible predicate."
        ),
    )
    parser.add_argument(
        "--authority-mode",
        choices=(AUTHORITY_MODE_ALL_DOMAIN, AUTHORITY_MODE_EXPLICIT_SET),
        default=AUTHORITY_MODE_ALL_DOMAIN,
        help="Authority selector mode. Defaults to all_domain.",
    )
    parser.add_argument(
        "--authority-id",
        action="append",
        default=[],
        help=(
            "Exact scaf_authority_id for explicit_set mode. Repeat as needed. "
            "An empty explicit set is valid."
        ),
    )
    parser.add_argument(
        "--omit-authority-id",
        action="append",
        default=[],
        help=(
            "Exact predicate-eligible scaf_authority_id to bounded-omit. Repeat as needed; "
            "requires --omission-basis."
        ),
    )
    parser.add_argument(
        "--omission-basis",
        default=None,
        help=(
            "Non-empty descriptive bounded-omission basis. Presence means applied:true; "
            "it does not define ranking or applicability."
        ),
    )
    parser.add_argument(
        "--profile",
        type=Path,
        default=None,
        help=(
            "Effective Project Profile YAML to consume. Defaults to "
            "examples/effective-project-profile.yaml."
        ),
    )
    parser.add_argument(
        "--project-application",
        type=Path,
        default=None,
        help=(
            "Project Application YAML corresponding to the selected profile. Defaults to "
            "examples/project-application.yaml."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    repo_root = _default_repo_root()
    try:
        generated = build_consumption_selection(
            repo_root,
            args.purpose,
            args.state,
            authority_mode=args.authority_mode,
            authority_ids=args.authority_id,
            omitted_authority_ids=args.omit_authority_id,
            omission_basis=args.omission_basis,
            profile_path=args.profile,
            project_application_path=args.project_application,
        )
    except ConsumptionSelectionBuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        print("CONSUMPTION SELECTION BUILD RESULT: FAIL", file=sys.stderr)
        return 1

    sys.stdout.buffer.write(generated)
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    sys.exit(main())
